# Generated by Django 6.0.2 on 2026-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
