# Generated by Django 6.0.2 on 2026-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='listing',
            name='genre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='language',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='listing',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
