# Generated by Django 6.0.2 on 2026-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hashtags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
