# Generated by Django 6.0.2 on 2026-02-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_listing_hashtags_userprofile_favorite_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('almost_new', 'Майже нова'), ('average', 'Середній стан'), ('poor', 'Поганий стан')], max_length=20),
        ),
    ]
